### ISSUE TITLE
Cannot checkout tagged commits newer than v3.7.0

### ISSUE THREAD

**Issue by skateman** [patternfly/angular-patternfly#281]
So I'm using [this script](https://github.com/patternfly/angular-patternfly-sass/blob/master/convert.sh) to generate `angular-patternfly-sass` from this repo. Now when I'm trying to check out the commit tagged as `v3.8.0` or `v3.8.1`, I receive an error.

```bash
$ git remote -v
origin	git@github.com:skateman/angular-patternfly-sass.git (fetch)
origin	git@github.com:skateman/angular-patternfly-sass.git (push)
source	git@github.com:patternfly/angular-patternfly.git (fetch)
source	git@github.com:patternfly/angular-patternfly.git (push)
upstream	git@github.com:patternfly/angular-patternfly-sass.git (fetch)
upstream	git@github.com:patternfly/angular-patternfly-sass.git (push)

$ git ls-remote --tags source | grep refs/tags/v3.8.0 | cut -f1
9346426567ce9c02e218de124df38eb909ede812

$ git checkout 9346426567ce9c02e218de124df38eb909ede812
fatal: reference is not a tree: 9346426567ce9c02e218de124df38eb909ede812

$ git ls-remote --tags source | grep refs/tags/v3.8.1 | cut -f1
f65df53af89dfa2b5b838617ac160b9e7901323f

$ git checkout f65df53af89dfa2b5b838617ac160b9e7901323f
fatal: reference is not a tree: f65df53af89dfa2b5b838617ac160b9e7901323f
```

This prevents me in releasing any new version of `angular-patternfly-sass` :cry:

**Comment by priley86** [comment]
was reviewing this with @jeff-phillips-18 just now. It appears there is currently an issue with our Travis build and removing old commits out of `master-dist` each time we issue a new build. The problem is these commits are tagged as release commits.  Will regroup with @dlabrecq and get you an answer soon.

**Comment by dlabrecq** [comment]
I'm looking at the commits for master and master-dist and they look the same to me with the exception of one extra commit for dist files. Why do you believe Travis is "removing old commits"?

When Travis starts a build, it's working from a detached head (i.e., the latest commit). In order to push build changes, we create a branch (i.e., git checkout -B master). We commit the dist changes here and push to master-dist. Not sure why this would be a problem, but the alternative is to merge changes with a branch?

**Comment by skateman** [comment]
@dlabrecq no, same :disappointed: 
```bash
$ git checkout f65df53
error: pathspec 'f65df53' did not match any file(s) known to git.
```

**Comment by dlabrecq** [comment]
FYI, that commit appears to be for 3.8.0 which didn't work for me. However, the commit for 3.8.1 does work for me:

git checkout 890de7c3fdfd785aa3c8cd0504c57706bcc405e7

**Comment by skateman** [comment]
Nope, not working here :( you probably have an older local copy. Can you give me 2 commit hashes which truly refer to the 3.8.0 and 3.8.1 versions to be able to release them? Please try to check them out on a newly cloned repository if they work. Thanks!

**Comment by priley86** [comment]
@skateman can you give this another try? We have decided to point these tags to latest, as the 3.8.0 and 3.8.1 commits were orphaned by our existing build process. This has been fixed going forward as @dlabrecq mentioned.

**Comment by skateman** [comment]
https://github.com/patternfly/angular-patternfly-sass/releases/tag/v3.8.0
https://github.com/patternfly/angular-patternfly-sass/releases/tag/v3.8.1

**Comment by skateman** [comment]
It works, thanks!
