### ISSUE TITLE
Any Plans to support semver Angular 1.4.x?

### ISSUE THREAD

**Issue by mtho11** [patternfly/angular-patternfly#37]

**Comment by erundle** [comment]
As of right now we haven't looked at 1.4.x support. I just upgraded the project to support Angular 1.3 so that gets us closer. 

I am not aware of anything particular in the project right now that should stop you from using 1.4 with the provided directives. Is your project currently using 1.4 or is this a nice to have?

**Comment by mtho11** [comment]
Yes, we are currently using 1.4.x. I wasn't looking for any specific functionality related to that, just a bower semver range that would support 1.4 more easily.
