### ISSUE TITLE
pf-toolbar ignoring changes in filterConfig.fields for dropdown button (not dropdown menu)

### ISSUE THREAD

**Issue by himdel** [patternfly/angular-patternfly#517]
Example: https://jsfiddle.net/s99cooja/
(ignore the console errors and missing images, would be nice if there was a CDN for angular-patternfly)

When `filterConfig.fields` changes, the dropdown *menu* gets correctly updated with the new options.

But the dropdown *button* and the select with values (when filterType = select) doesn't get updated and still shows the (now no longer existing) option that had been chosen before `fields` changed.

There seems to be no workaround.

**Comment by dtaylor113** [comment]
Hi, I cannot reproduce this.  I added your example to the pfToolbar ngDoc:

![image](https://user-images.githubusercontent.com/12733153/29630139-285f7baa-8809-11e7-99e2-031c0fc9c490.png)
...
![image](https://user-images.githubusercontent.com/12733153/29630152-382d253c-8809-11e7-9844-162b608d32e8.png)

**Clicked on Break! button**

![image](https://user-images.githubusercontent.com/12733153/29630181-531c0ae8-8809-11e7-91c1-a7138dc3edf7.png)

**Filter Dropdown button and menu updated as expected**

I did see the error in your jsfiddle, so perhaps the updating schema of pfToolbar and/or pfFilter has changed since this issue was filed.  Please re-open if you discover it has not been fixed.

**Comment by himdel** [comment]
@dtaylor113 Will do :) is there a way to properly include patternfly in a jsfiddle or similar?

(Can't test versions newer than 3.23.1 with the manageiq bundle.)

**Comment by dtaylor113** [comment]
Ok, closing this issue.
