### ISSUE TITLE
Docks out of date about drawer expanded state

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#552]
Either out of date, or something broke in the build process:

<img width="602" alt="screen shot 2017-08-04 at 10 43 31 am" src="https://user-images.githubusercontent.com/280512/28973657-e6378472-7901-11e7-9943-b97492a64c71.png">

We previously noted the `span>` on line 15 being incomplete, but it appears to also be missing the entire "drawerExpanded" section (originally was another +/-20 lines of HTML). 

For example, I'm working off of an example template that has the following:

```html
<div ng-if="!drawerExpanded">
   <!-- collapsed state things... -->
</div>
<div ng-if="drawerExpanded">
   <!-- expanded state things... -->
</div>
```
@jeff-phillips-18 @cdcabrera

**Comment by jeff-phillips-18** [comment]
The example current does not show anything different between expanded and collapsed state. Previously it adjusted due to stylings that did not work well in both states. The changes in patternfly styling allowed this to work without having to change the html based on the expanded state.

As for the example you are using, looks like both are checking !drawExpanded, the later should likely be checking drawerExpanded.

If desirable, we can add content when expanded to broaden the example.

**Comment by benjaminapetersen** [comment]
Yeah, i think using the same HTML for both makes better sense.  It may just be that the example `notification-body.html` & the actual rendered example on the page are out of date.  For example, when i look at the source of the rendered after a toggle open, I see classes like 'expanded-notification' that do not appear in the example, which intro the use of `flex` (which makes sense).

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen Did you find this is still an issue?

**Comment by benjaminapetersen** [comment]
Yeah lets nix this, I may have had a weird cache issue or something.
