### ISSUE TITLE
The base dashboard card should have a loading state

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#658]
The base dashboard card (http://www.patternfly.org/pattern-library/cards/base-card/#/design) should have a loading state similar to this:
<img width="144" alt="screen shot 2017-10-23 at 9 52 33 am" src="https://user-images.githubusercontent.com/12504403/31893389-6c11d082-b7d9-11e7-9893-64d8429b5b2e.png">

We need to verify with Visuals which spinner should be used, as i think we want animation here.   @jennyhaines what are your thoughts?

**Comment by jennyhaines** [comment]
@serenamarie125 I think that the large size regular PatternFly [spinner](https://www.patternfly.org/pattern-library/widgets/#spinner) would be nice in this spot. I don't think a stagnant patternFly icon would work in this case, since this spinner should denote "currently loading" rather than a status within a list of statuses.

**Comment by beanh66** [comment]
FYI @serenamarie125 patternFly design story created here 
https://github.com/patternfly/patternfly-design/issues/466

**Comment by jennyhaines** [comment]
@beanh66 - I think the animated spinner is pretty universal. In my mind, I'd only show the spinner (no text).
