### ISSUE TITLE
The Sass file _angular-patternfly.scss does not include Datepicker & Vertical-navigation

### ISSUE THREAD

**Issue by wywywywy** [patternfly/angular-patternfly#772]
Found a bug.

In the Sass file `angular-patternfly/styles/_angular-patternfly.scss` - it seems to be missing `datepicker` and `vertical-navigation` imports, even though they are there in the Less file.

**Comment by jeff-phillips-18** [comment]
Thanks @wywywywy, are you interested in contributing a fix?

**Comment by wywywywy** [comment]
Yes sure I'll submit a PR later today.

**Comment by dtaylor113** [comment]
Thanks @wywywywy !

**Comment by dtaylor113** [comment]
Hi @wywywywy, you've probably already seen this, but if not:  https://github.com/patternfly/angular-patternfly#less-to-sass-conversion

Is the issue with `datepicker` and `vertical-navigation` imports due to:

"Note: When a Less file is added/deleted/renamed it needs to be updated in the main Less import file /styles/angular-patternfly.less and the main Sass import file styles/_angular-patternfly.scss."

Thanks!

**Comment by wywywywy** [comment]
Yes it is.

I think someone just forgot to put those 2 lines in.
